django_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('task.urls', namespace='task')),
]

task/urls.py
from django.conf.urls import url
from task import views

urlpatterns = [
    url(r'^$', views.MiloUsersList.as_view(), name='users'),
    url(r'^add/$', views.MiloUserCreate.as_view(), name='add_user'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.MiloUserUpdate.as_view(), name='edit_user'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.MiloUserDelete.as_view(), name='delete_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.MiloUserDetails.as_view(), name='user_details'),
    url(r'^dowload/$', views.MiloUserDownload.as_view(), name='dowload_users_list'),
]

task/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.timezone import now
from random import randint


class MiloUser(AbstractUser):
    date_of_birth = models.DateField(default=now,
                                                                            verbose_name='Birthday date'
                                                                            )
    random_int = models.IntegerField(default=randint(1,100),
                                                                            verbose_name='Random int',
                                                                            validators=[MinValueValidator(1), MaxValueValidator(100)]
                                                                            )

    def get_fields(self):
        return [(field.verbose_name, field._get_val_from_obj(self)) for field in MiloUser._meta.fields]

task/forms.py
from django.forms import ModelForm

from models import MiloUser


class AddUserForm(ModelForm):
    class Meta:
        model = MiloUser
        fields = ['username', 'first_name', 'last_name', 'password', 'date_of_birth']


class EditUserForm(ModelForm):
    class Meta:
        model = MiloUser
        fields = ['username', 'first_name', 'last_name', 'date_of_birth']

task/views.py
import csv

from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.urls import reverse

from models import MiloUser
from forms import AddUserForm, EditUserForm
from templatetags import task_extras


class CSVResponseMixin(object):
    csv_filename = 'csvfile.csv'

    def get_csv_filename(self):
        return self.csv_filename

    def render_to_csv(self, data):
        response = HttpResponse(content_type='text/csv')
        cd = 'attachment; filename="{0}"'.format(self.get_csv_filename())
        response['Content-Disposition'] = cd

        writer = csv.writer(response)
        for row in data:
            writer.writerow(row)

        return response


class MiloUserDownload(CSVResponseMixin, View):
    csv_filename = 'Users list.csv'
    users = MiloUser.objects.all()
    data = [[user.username, user.date_of_birth, user.random_int, 
                        task_extras.is_permited(user.date_of_birth),
                        task_extras.bizz_fuzz(user.random_int)] for user in users]

    def get(self, request, *args, **kwargs):
        return self.render_to_csv(self.data)


class MiloUsersList(ListView):
    model = MiloUser
    context_object_name = 'users'
    template_name = 'task/users_list.html'


class MiloUserDetails(DetailView):
    model = MiloUser
    context_object_name = 'user'
    template_name = 'task/user_details.html'


class MiloUserCreate(CreateView):
    model = MiloUser
    form_class = AddUserForm
    template_name = 'task/user_create_form.html'

    def get_success_url(self):
        return reverse('task:users')


class MiloUserUpdate(UpdateView):
    model = MiloUser
    form_class = EditUserForm
    template_name = 'task/user_edit_form.html'

    def get_success_url(self):
        return reverse('task:users')


class MiloUserDelete(DeleteView):
    model = MiloUser
    template_name = 'task/user_delete_form.html'

    def get_success_url(self):
        return reverse('task:users')

task/templates/task/base.html
{% load task_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Milo Solutions test</title>
  </head>
  <body>
        <div class="container">
          <div class="row">
              {% block body %}
              {% endblock body %}
          </div>
        </div>
  </body>
</html>

task/templates/task/user_create_form.html
{% extends 'task/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
    <form action="" method="POST">{% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock body %}

task/templates/task/user_delete_form.html
{% extends 'task/base.html' %}

{% block body %}
    <form action="" method="POST">{% csrf_token %}
        <p>Sure about deleting user "{{ object }}" ???</p>
        <button type="submit" class="btn btn-success">Definitely YES!!!</button>
    </form>
{% endblock body %}

task/templates/task/user_details.html
{% extends "task/base.html" %}
{% load task_extras %}

{% block body %}
    {% for name, value in user.get_fields %}
        <p>
            <label>{{ name }}:</label>
            <span>{{ value|default:"Not available" }}</span>
        </p>
    {% endfor %}
{% endblock %}

task/templates/task/user_edit_form.html
{% extends 'task/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
    <form action="" method="POST">{% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success">Edit</button>
    </form>
{% endblock body %}

task/templates/task/users_list.html
{% extends "task/base.html" %}
{% load task_extras %}
{% block body %}

<a href="{% url 'task:add_user' %}">Add new user</a>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            {% for user in users|slice:":1" %}
            <tr>
                <td>{% get_verbose_name user "username" %}</td>
                <td>{% get_verbose_name user "date_of_birth" %}</td>
                <td>{% get_verbose_name user "random_int" %}</td>
                <th>Allowed</th>
                <th>BizzFuzz</th>
            </tr>
            {% endfor %}
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td><a href="{% url 'task:user_details' user.id %}">{{ user.username }}</a></td>
                <td>{{ user.date_of_birth }}</td>
                <td>{{ user.random_int }}</td>
                <td>{% is_permited user.date_of_birth %}</td>
                <td>{% bizz_fuzz user.random_int %}</td>
                <td><a href="{% url 'task:edit_user' user.id %}">Edit</a></td>
                <td><a href="{% url 'task:delete_user' user.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'task:dowload_users_list' %}">Download users list</a>
</div>
{% endblock %}